### ISSUE TITLE
All blocks are walkthrough now

### ISSUE THREAD

**Issue by SMOLKEYS** [sk7725/Testers#3]
Everytime i place a tester block, its unusable and unremovable + its walkthrough now

**Comment by LixieWulf** [comment]
This is an issue with your device, not Testers. Testers is a JS mod, which does not run on iOS or android 4.4.2 or below.

edit: Yes, I have used Testers fine.

**Comment by SMOLKEYS** [comment]
Im running android 9.

**Comment by LixieWulf** [comment]
Huh. Can't reproduce, make sure other mods aren't interfering.

**Comment by SMOLKEYS** [comment]
Yep, its mod interference.

**Comment by QmelZ** [comment]
*which mod though*

**Comment by ThePythonGuy3** [comment]
yogurt mod

**Comment by SMOLKEYS** [comment]
aegh forgot to give mods, lemme do a bit of testing
